#name on jobs => must have
name: "my first"

on: push

env:
 WORKFLOW_LEVEL: 'this value comes from the workflow level'

jobs:
  first-job: 
    name: 'first job'

    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']

    runs-on: ${{matrix.os}}
    env:
     JOB_LEVEL_1: 'THIS VALUE COMES FROM THE JOB LEVEL 1'
    steps:
    - name: output value ${{matrix.os}}
      id: first
      shell: bash
      run: |
        echo "OS: ${{matrix.os}}"