#name on jobs => must have
name: "my first"

on: ['push' , 'pull_request']

env:
 WORKFLOW_LEVEL: 'this value comes from the workflow level'

jobs:
  first-job: 
    name: 'first job'
    runs-on: 'ubuntu-latest'
    steps:
    - name: output value 1-1
      id: first
      shell: bash
      run: |
        echo "job 1"
    - name: output value 1-2
      shell: bash
      run: |
        echo "job 1-2"

  second-job: 
    name: 'second job'
    runs-on: 'ubuntu-latest'
    steps:
    - name: output value 2-1
      id: second
      shell: bash
      run: |
        echo "job 2"